# Generated by Django 2.0 on 2018-11-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('carrier', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(blank=True, db_column='price', default='0')),
                ('full_price', models.FloatField(blank=True, db_column='full_price', default='0')),
                ('description', models.TextField(blank=True, db_column='description', default='')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('ip', models.CharField(default='', max_length=100)),
                ('user_agent', models.CharField(default='', max_length=100)),
                ('id_offer', models.CharField(default='', max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
