# Generated by Django 2.0 on 2018-11-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='title',
            new_name='product',
        ),
    ]
