# Generated by Django 2.0 on 2018-11-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastweb', '0003_auto_20181114_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
